### PR TITLE
Update profile image size

### PR DESCRIPTION
**Pull request by christianbriggs**
Update the profile image to 1280x640. Also add the image to the repo and update the link in the readme.

### CODE REVIEW

**Review by alies-dev — APPROVED** [review]
looks great, thanks a lot, Christian! 👍

**Comment by christianbriggs** [comment]
@lptn I know there are two ways to use images in Github markdown files. If the method i have used here is not the best, i can use the method that adds the image by uploading it here and referring to the new url.
IxDF-github-profile

**Comment by alies-dev** [comment]
@christianbriggs yes, a method with relative link doesn't work for some cases (e.g. if you selected a non-default branch like this: https://github.com/InteractionDesignFoundation/.github/tree/update-profile-image-size/profile). We don't have guidelines for that, but my personal preference is absolute links generated using RTE - they just work in all cases

**Comment by christianbriggs** [comment]
Thanks @lptn . I am uploading the new version from @dskrok and using the absolute url. 
IxDF-Hero-1500x500

**Pull request merged**
